package dev.ushki.livedndlist.enums;

public enum CharacterAlignment {
  LAWFUL_GOOD, NEUTRAL_GOOD, CHAOTIC_GOOD,
  LAWFUL_NEUTRAL, TRUE_NEUTRAL, CHAOTIC_NEUTRAL,
  LAWFUL_EVIL, NEUTRAL_EVIL, CHAOTIC_EVIL,
  UNALIGNED
}
