package dev.ushki.livedndlist.enums;

public enum DndClassFeatureType {
  CLASS_TABLE_DATA, PROFICIENCY_BONUS, CLASS_LEVEL_FEATURE, PROFICIENCIES, STARTING_EQUIPMENT,
  CLASS_FEATURE_OPTION_LIST, SPELL_SLOTS, CORE_TRAITS_TABLE
}
