[ca]
distinguished_name = ca_distinguished_name
x509_extensions = ca_extensions
prompt = no

[ca_distinguished_name]
C = BY
ST = Minsk
L = Minsk
O = Ushki
CN = CA

[ca_extensions]
basicConstraints = critical, CA:TRUE

[victoriametrics]
distinguished_name = victoriametrics_distinguished_name
x509_extensions = victoriametrics_extensions
prompt = no

[victoriametrics_distinguished_name]
C = BY
ST = Minsk
L = Minsk
O = Ushki
CN = victoriametrics

[victoriametrics_extensions]
basicConstraints = critical, CA:FALSE
subjectAltName = @victoriametrics_sans

[victoriametrics_sans]
IP.1 = 127.0.0.1
DNS.1 = localhost
DNS.2 = victoriametrics
DNS.3 = victoriametrics.live-dnd-list.duckdns.org
DNS.4 = live-dnd-list.duckdns.org
