package dev.ushki.live_dnd_list.enums;

public enum CharacterRace {
    HUMAN, ELF, DWARF, HALFLING, GNOME, HALF_ELF, HALF_ORC,
    TIEFLING, DRAGONBORN, AARAKOCRA, GENASI, GOLIATH, TABAXI,
    KENKU, FIRBOLG, LIZARDFOLK, TRITON, AASIMAR, BUGBEAR,
    GOBLIN, HOBGOBLIN, KOBOLD, ORC, YUAN_TI, TORTLE, WARFORGED,
    CHANGELING, KALASHTAR, SHIFTER, CUSTOM
}
