CREATE TYPE character_alignment_type AS ENUM (
    'LAWFUL_GOOD', 'NEUTRAL_GOOD', 'CHAOTIC_GOOD',
    'LAWFUL_NEUTRAL', 'TRUE_NEUTRAL', 'CHAOTIC_NEUTRAL',
    'LAWFUL_EVIL', 'NEUTRAL_EVIL', 'CHAOTIC_EVIL', 'UNALIGNED'
);

CREATE TYPE ability_type AS ENUM (
    'STRENGTH', 'DEXTERITY', 'CONSTITUTION', 
    'INTELLIGENCE', 'WISDOM', 'CHARISMA'
);

CREATE TYPE equipment_type AS ENUM (
    'WEAPON', 'ARMOR', 'SHIELD', 'GEAR', 
    'TOOL', 'CONSUMABLE', 'TREASURE', 'MAGIC_ITEM'
);

CREATE TYPE skill_type AS ENUM (
    'ACROBATICS', 'ANIMAL_HANDLING', 'ARCANA', 'ATHLETICS',
    'DECEPTION', 'HISTORY', 'INSIGHT', 'INTIMIDATION',
    'INVESTIGATION', 'MEDICINE', 'NATURE', 'PERCEPTION',
    'PERFORMANCE', 'PERSUASION', 'RELIGION', 'SLEIGHT_OF_HAND',
    'STEALTH', 'SURVIVAL'
);

CREATE TYPE spell_school_type AS ENUM (
    'ABJURATION', 'CONJURATION', 'DIVINATION', 'ENCHANTMENT',
    'EVOCATION', 'ILLUSION', 'NECROMANCY', 'TRANSMUTATION'
);

CREATE TYPE role_type AS ENUM (
    'ROLE_USER', 'ROLE_ADMIN');
