CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    role role_type NOT NULL DEFAULT 'ROLE_USER',
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS races (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    asi_description TEXT,
    age TEXT,
    alignment TEXT,
    size_description VARCHAR(255),
    size_raw VARCHAR(255),
    speed_description TEXT,
    languages TEXT,
    vision TEXT,
    traits TEXT,
    document_slug VARCHAR(255),
    document_title VARCHAR(255),
    document_license_url VARCHAR(255),
    document_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS subraces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description TEXT,
    traits TEXT,
    asi_description TEXT,
    document_slug VARCHAR(255),
    document_title VARCHAR(255),
    document_url VARCHAR(255),
    race_id BIGINT NOT NULL,
    CONSTRAINT fk_subrace_race FOREIGN KEY (race_id) REFERENCES races(id) ON DELETE CASCADE
);
CREATE INDEX idx_subraces_race_id ON subraces(race_id);

CREATE TABLE IF NOT EXISTS ability_score_increases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value INTEGER NOT NULL,
    attributes TEXT NOT NULL,   -- comma‑separated list of ability names
    race_id BIGINT,
    subrace_id BIGINT,
    CONSTRAINT fk_asi_race FOREIGN KEY (race_id) REFERENCES races(id) ON DELETE CASCADE,
    CONSTRAINT fk_asi_subrace FOREIGN KEY (subrace_id) REFERENCES subraces(id) ON DELETE CASCADE
);
CREATE INDEX idx_asi_race_id ON ability_score_increases(race_id);
CREATE INDEX idx_asi_subrace_id ON ability_score_increases(subrace_id);

CREATE TABLE IF NOT EXISTS speeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    walk_speed INTEGER,
    fly_speed INTEGER,
    swim_speed INTEGER,
    climb_speed INTEGER,
    burrow_speed INTEGER,
    race_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_speed_race FOREIGN KEY (race_id) REFERENCES races(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS spells (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    level INTEGER NOT NULL,
    school spell_school_type,
    casting_time VARCHAR(255),
    range VARCHAR(255),
    components VARCHAR(255),
    duration VARCHAR(255),
    concentration BOOLEAN DEFAULT FALSE,
    ritual BOOLEAN DEFAULT FALSE,
    description TEXT,
    higher_levels TEXT
);

CREATE TABLE IF NOT EXISTS dnd_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    hit_dice VARCHAR(50),
    hp_at_1st_level VARCHAR(255),
    hp_at_higher_levels TEXT,
    prof_armor TEXT,
    prof_weapons TEXT,
    prof_tools TEXT,
    prof_saving_throws TEXT,
    prof_skills TEXT,
    equipment TEXT,
    level_table TEXT,
    spellcasting_ability VARCHAR(255),
    subtypes_name VARCHAR(255),
    document_slug VARCHAR(255),
    document_title VARCHAR(255),
    document_license_url VARCHAR(255),
    document_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS archetypes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description TEXT,
    document_slug VARCHAR(255),
    document_title VARCHAR(255),
    document_license_url VARCHAR(255),
    document_url VARCHAR(255),
    dnd_class_id BIGINT NOT NULL,
    CONSTRAINT fk_archetype_class FOREIGN KEY (dnd_class_id) REFERENCES dnd_classes(id) ON DELETE CASCADE
);
CREATE INDEX idx_archetypes_class_id ON archetypes(dnd_class_id);

CREATE TABLE IF NOT EXISTS characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    race_id BIGINT NOT NULL,
    alignment character_alignment_type,
    background VARCHAR(255),
    experience_points INTEGER DEFAULT 0,
    portrait_url VARCHAR(512),
    level INTEGER DEFAULT 1,
    max_hit_points INTEGER DEFAULT 10,
    current_hit_points INTEGER DEFAULT 10,
    temporary_hit_points INTEGER DEFAULT 0,
    armor_class INTEGER DEFAULT 10,
    initiative INTEGER DEFAULT 0,
    speed INTEGER DEFAULT 30,
    proficiency_bonus INTEGER DEFAULT 2,
    hit_dice VARCHAR(50),
    death_save_successes INTEGER DEFAULT 0,
    death_save_failures INTEGER DEFAULT 0,
    spellcasting_ability ability_type,
    features_and_traits TEXT,
    backstory TEXT,
    personality_traits TEXT,
    ideals TEXT,
    bonds TEXT,
    flaws TEXT,
    notes TEXT,
    is_public BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    -- Embedded AbilityScores
    strength INTEGER NOT NULL DEFAULT 10,
    dexterity INTEGER NOT NULL DEFAULT 10,
    constitution INTEGER NOT NULL DEFAULT 10,
    intelligence INTEGER NOT NULL DEFAULT 10,
    wisdom INTEGER NOT NULL DEFAULT 10,
    charisma INTEGER NOT NULL DEFAULT 10,

    -- Embedded DndCurrency
    copper INTEGER DEFAULT 0,
    silver INTEGER DEFAULT 0,
    electrum INTEGER DEFAULT 0,
    gold INTEGER DEFAULT 0,
    platinum INTEGER DEFAULT 0,

    CONSTRAINT fk_character_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_character_race FOREIGN KEY (race_id) REFERENCES races(id) ON DELETE RESTRICT
);
CREATE INDEX idx_characters_user_id ON characters(user_id);
CREATE INDEX idx_characters_race_id ON characters(race_id);

CREATE TABLE IF NOT EXISTS character_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    archetype_id BIGINT,
    level INTEGER DEFAULT 1,
    CONSTRAINT fk_charclass_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_charclass_class FOREIGN KEY (class_id) REFERENCES dnd_classes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_charclass_archetype FOREIGN KEY (archetype_id) REFERENCES archetypes(id) ON DELETE SET NULL
);
CREATE INDEX idx_charclasses_character_id ON character_classes(character_id);
CREATE INDEX idx_charclasses_class_id ON character_classes(class_id);

CREATE TABLE IF NOT EXISTS skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL,
    skill_type skill_type NOT NULL,
    proficiency BOOLEAN DEFAULT FALSE,
    expertise BOOLEAN DEFAULT FALSE,
    bonus INTEGER DEFAULT 0,
    CONSTRAINT fk_skill_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT unique_character_skill UNIQUE (character_id, skill_type)
);
CREATE INDEX idx_skills_character_id ON skills(character_id);

CREATE TABLE IF NOT EXISTS equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    quantity INTEGER DEFAULT 1,
    weight DOUBLE PRECISION,
    equipped BOOLEAN DEFAULT FALSE,
    attuned BOOLEAN DEFAULT FALSE,
    type equipment_type,
    damage VARCHAR(255),
    damage_type VARCHAR(255),
    properties VARCHAR(255),
    CONSTRAINT fk_equipment_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE
);
CREATE INDEX idx_equipment_character_id ON equipment(character_id);

CREATE TABLE IF NOT EXISTS character_saving_throws (
    character_id BIGINT NOT NULL,
    saving_throw_proficiencies ability_type NOT NULL,
    CONSTRAINT pk_char_saving_throws PRIMARY KEY (character_id, saving_throw_proficiencies),
    CONSTRAINT fk_saving_throws_char FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS character_spells (
    character_id BIGINT NOT NULL,
    spell_id BIGINT NOT NULL,
    CONSTRAINT pk_char_spells PRIMARY KEY (character_id, spell_id),
    CONSTRAINT fk_charspell_character FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT fk_charspell_spell FOREIGN KEY (spell_id) REFERENCES spells(id) ON DELETE CASCADE
);