-- 1. Create Documents table (with Embedded Publisher and GameSystem)
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(255),
    name VARCHAR(255),
    type VARCHAR(255),
    display_name VARCHAR(255),
    permalink VARCHAR(255),
    -- Embedded Publisher
    publisher_name VARCHAR(255),
    publisher_key VARCHAR(255),
    -- Embedded GameSystem
    system_name VARCHAR(255),
    system_key VARCHAR(255)
);

-- 2. Create Backgrounds table
CREATE TABLE IF NOT EXISTS backgrounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    description TEXT, -- Maps to 'desc' in JPA
    document_id BIGINT,
    CONSTRAINT fk_background_document FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL
);

-- 3. Create Background Benefits (ElementCollection table)
-- Note: As an Embeddable in a CollectionTable, it doesn't have its own ID
CREATE TABLE IF NOT EXISTS background_benefits (
    background_id BIGINT NOT NULL,
    name VARCHAR(255),
    description TEXT, -- Maps to @Column(columnDefinition = "TEXT")
    type VARCHAR(255),
    CONSTRAINT fk_benefits_background FOREIGN KEY (background_id) REFERENCES backgrounds(id) ON DELETE CASCADE
);
CREATE INDEX idx_background_benefits_bg_id ON background_benefits(background_id);

-- 4. Migrate Characters table
ALTER TABLE characters DROP COLUMN IF EXISTS background;

ALTER TABLE characters ADD COLUMN background_id BIGINT;

-- Add constraint and index
ALTER TABLE characters
    ADD CONSTRAINT fk_character_background
    FOREIGN KEY (background_id) REFERENCES backgrounds(id) ON DELETE SET NULL;

CREATE INDEX idx_characters_background_id ON characters(background_id);