DROP TABLE IF EXISTS ability_score_increases;
DROP TABLE IF EXISTS subraces;

ALTER TABLE races
    RENAME COLUMN slug TO key;

ALTER TABLE races
    ADD COLUMN subspecies      BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN parent_race_key VARCHAR(255),
    ADD COLUMN document_id     BIGINT;

ALTER TABLE races
    DROP COLUMN IF EXISTS asi_description,
    DROP COLUMN IF EXISTS age,
    DROP COLUMN IF EXISTS alignment,
    DROP COLUMN IF EXISTS size_description,
    DROP COLUMN IF EXISTS size_raw,
    DROP COLUMN IF EXISTS speed_description,
    DROP COLUMN IF EXISTS languages,
    DROP COLUMN IF EXISTS vision,
    DROP COLUMN IF EXISTS traits,
    DROP COLUMN IF EXISTS document_slug,
    DROP COLUMN IF EXISTS document_title,
    DROP COLUMN IF EXISTS document_license_url,
    DROP COLUMN IF EXISTS document_url;

ALTER TABLE races
    ADD CONSTRAINT fk_races_document
        FOREIGN KEY (document_id) REFERENCES documents (id);

CREATE INDEX IF NOT EXISTS idx_races_document_id ON races (document_id);

CREATE TABLE IF NOT EXISTS race_traits
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    type        VARCHAR(255),
    trait_order INTEGER,
    race_id     BIGINT       NOT NULL,
    CONSTRAINT fk_race_traits_race
        FOREIGN KEY (race_id) REFERENCES races (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_race_traits_race_id ON race_traits (race_id);
