-- =====================================================
-- 1. Create new dnd_classes table
-- =====================================================

CREATE TABLE IF NOT EXISTS dnd_classes_new
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key                   VARCHAR(255) NOT NULL UNIQUE,
    name                  VARCHAR(255) NOT NULL,
    description           TEXT,
    hit_dice              VARCHAR(50),
    parent_dnd_class_name VARCHAR(255),
    parent_dnd_class_key  VARCHAR(255),
    document_id           BIGINT,
    subclass_of_id        BIGINT,
    saving_throws         VARCHAR(255)[],
    CONSTRAINT fk_dnd_class_new_document FOREIGN KEY (document_id) REFERENCES documents (id),
    CONSTRAINT fk_dnd_class_new_parent FOREIGN KEY (subclass_of_id) REFERENCES dnd_classes_new (id)
);

CREATE INDEX idx_dnd_classes_new_key ON dnd_classes_new (key);
CREATE INDEX idx_dnd_classes_new_subclass_of ON dnd_classes_new (subclass_of_id);
CREATE INDEX idx_dnd_classes_new_document ON dnd_classes_new (document_id);


-- =====================================================
-- 2. Create features tables
-- =====================================================

CREATE TABLE IF NOT EXISTS dnd_class_features
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key          VARCHAR(255) NOT NULL UNIQUE,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    feature_type VARCHAR(50),
    dnd_class_id BIGINT       NOT NULL,
    CONSTRAINT fk_feature_class FOREIGN KEY (dnd_class_id)
        REFERENCES dnd_classes_new (id) ON DELETE CASCADE
);

CREATE INDEX idx_dnd_class_features_class ON dnd_class_features (dnd_class_id);
CREATE INDEX idx_dnd_class_features_key ON dnd_class_features (key);

CREATE TABLE IF NOT EXISTS dnd_class_feature_gained_at
(
    feature_id BIGINT  NOT NULL,
    level      INTEGER NOT NULL,
    detail     VARCHAR(255),
    CONSTRAINT fk_gained_at_feature FOREIGN KEY (feature_id)
        REFERENCES dnd_class_features (id) ON DELETE CASCADE
);

CREATE INDEX idx_gained_at_feature ON dnd_class_feature_gained_at (feature_id);

CREATE TABLE IF NOT EXISTS dnd_class_table_data
(
    feature_id   BIGINT       NOT NULL,
    level        INTEGER      NOT NULL,
    column_value VARCHAR(255) NOT NULL,
    CONSTRAINT fk_table_data_feature FOREIGN KEY (feature_id)
        REFERENCES dnd_class_features (id) ON DELETE CASCADE
);

CREATE INDEX idx_table_data_feature ON dnd_class_table_data (feature_id);


-- =====================================================
-- 3. Create new character_classes table
-- =====================================================

CREATE TABLE IF NOT EXISTS character_classes_new
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT  NOT NULL,
    class_id     BIGINT  NOT NULL,
    level        INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_charclass_new_character
        FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE,
    CONSTRAINT fk_charclass_new_class
        FOREIGN KEY (class_id) REFERENCES dnd_classes_new (id) ON DELETE RESTRICT,
    CONSTRAINT uk_character_class_new UNIQUE (character_id, class_id)
);

CREATE INDEX idx_charclasses_new_character_id ON character_classes_new (character_id);
CREATE INDEX idx_charclasses_new_class_id ON character_classes_new (class_id);


-- =====================================================
-- 4. Drop old tables
-- =====================================================

DROP TABLE IF EXISTS character_classes;
DROP TABLE IF EXISTS archetypes;
DROP TABLE IF EXISTS dnd_classes;


-- =====================================================
-- 5. Rename new tables to final names
-- =====================================================

ALTER TABLE dnd_classes_new
    RENAME TO dnd_classes;
ALTER TABLE character_classes_new
    RENAME TO character_classes;


-- =====================================================
-- 6. Rename indexes
-- =====================================================

ALTER INDEX idx_dnd_classes_new_key RENAME TO idx_dnd_classes_key;
ALTER INDEX idx_dnd_classes_new_subclass_of RENAME TO idx_dnd_classes_subclass_of;
ALTER INDEX idx_dnd_classes_new_document RENAME TO idx_dnd_classes_document;
ALTER INDEX idx_charclasses_new_character_id RENAME TO idx_charclasses_character_id;
ALTER INDEX idx_charclasses_new_class_id RENAME TO idx_charclasses_class_id;


-- =====================================================
-- 7. Rename constraints
-- =====================================================

ALTER TABLE dnd_classes
    RENAME CONSTRAINT fk_dnd_class_new_document TO fk_dnd_class_document;
ALTER TABLE dnd_classes
    RENAME CONSTRAINT fk_dnd_class_new_parent TO fk_dnd_class_parent;
ALTER TABLE character_classes
    RENAME CONSTRAINT fk_charclass_new_character TO fk_charclass_character;
ALTER TABLE character_classes
    RENAME CONSTRAINT fk_charclass_new_class TO fk_charclass_class;
ALTER TABLE character_classes
    RENAME CONSTRAINT uk_character_class_new TO uk_character_class;