# .github/workflows/deploy.yml

name: Build, Test and Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.GCP_VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.GCP_VM_HOST_KEY }}" > ~/.ssh/known_hosts

      - name: Debug Secrets
        run: |
          echo "VM User: ${{ secrets.GCP_VM_USER }}"
          echo "VM IP is set: ${{ secrets.GCP_VM_IP != '' }}"
          echo "VM IP Length: ${{ env.IP_LENGTH }}"
        env:
          IP_LENGTH: ${{ secrets.GCP_VM_IP }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} '
          echo "✅ Connection works!"
          '
            cd /home/wartim9494/liveDndList
            git pull
            docker-compose up -d --build
            docker image prune -f
            echo "--- Deployment successful! ---"
          '
